version: '3.4'

services:
  test:
    image: test
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000





  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
  
  
  
        
  
  
