version: '3.4'

services:
  test:
    image: test
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000


volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
  portainer-data:
    driver: local



  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
  
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "7407:9090"

    depends_on:
    - cadvisor
    - node_exporter
    restart: unless-stopped
   
        
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 7402:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 7403:6379  

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'  
